root_dir: D:\cjh\Adversarial_Robustness/
datasets_dir: ${root_dir}datasets/
ckpt_dir: ${root_dir}ckpt/
log_dir: D:\cjh\Adversarial_Robustness/log//CIFAR10_ResNet_2023-02-24-12-32-30.txt
optimizer: Adam
lr: 0.001
weight_decay: 0.0001
max_epochs: 50
num_workers: 0
batch_size: 128
save_ckpt_interval_epoch: 1
val_split: 0.1
test_split: 0.1
shuffle_dataset: true
random_seed: 42
config_file: null
datasets: CIFAR10
model_name: ResNet
resume: false
use_cuda: true
